
---
- hosts: [g-cls]
  remote_user: mlu@boardbooks.com 
  serial: 2
  become: yes
  become_method: sudo
  tasks:
  - name: Run Backup Script
    script: /var/ansible/opt/mdb-playbooks/MDB_Backup_corp.py

